#![doc = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/README.md"))]

#[doc(hidden)]
pub use ::perstruct_proc_macros::perstruct;

/// Result of the method `from_map` of a struct generated by the `perstruct` macro.
/// It contains the deserialized struct, a list of deserialization errors and a list of unknown fields.
/// The deserialization errors are a list of tuples containing the name of the field and the error message.
/// The unknown fields are a list of keys in the map that did not match any field.
pub struct PerstructLoadResult<T> {
    pub value: T,
    pub deserialization_errors: Vec<(&'static str, String)>,
    pub unknown_fields: Vec<String>,
}
